### ISSUE TITLE
Code/GitHub links

### ISSUE THREAD

**Issue by pelmered** [wpse/awesome-swedish-plugins#2]
For most open source plugins the development occurs on GitHub or some other code hosting that is not the WordPress.org SVN repo. Therefore I think there should be links to GitHub or the place where the real development occurs in addition to the official plugin page.

**Comment by khromov** [comment]
@pelmered Maybe a "[Contribute] link at the end, so the template would become:
`[Plugin name](link) text - [Author name](link) [[Contribute]](link)`

Example:
[Papi](https://wp-papi.github.io/) - Add custom fields and a better page type way of thinking to WordPress. - By [Fredrik Forsmo](https://twitter.com/frozzare) [[Contribute]](https://github.com/wp-papi/papi)

Thoughts, @frozzare

**Comment by frozzare** [comment]
That's looks good @khromov!

**Comment by pelmered** [comment]
Yes, that would solve this @khromov!

**Comment by frozzare** [comment]
Added a few contribute links now. Did write it like this `[Author name](link) - [[Contribute]](link)` with a dash between author and contribute. Feel free to add pull request with contribute links!
